// src/lib/components/time/Time.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let time = $state(new Date());
	let hours = $derived(time.getHours());
	let minutes = $derived(time.getMinutes());
	onMount(() => {
		const interval = setInterval(() => {
			time = new Date();
		}, 1000);
		return () => {
			clearInterval(interval);
		};
	});
</script>

<div class="rect">
	<p>{hours}:{minutes.toString().padStart(2, '0')}</p>
</div>

<style>
	p {
		height: 14px;
		font-family: 'Pixelated MS Sans Serif', sans-serif;
		font-size: smaller;
		font-weight: 500;
	}
	.rect {
		height: 21px;
		display: flex;
		align-items: center;
	}
</style>

// src/components/time/Time.tsx
import { useEffect, useState } from "react";
import styled from "styled-components";

const TimeDiv = styled.div`
  height: 21px;
  display: block;
  align-content: center;
  font-size: 11px;
  padding: 0 4px;
`;

function Time() {
  const [time, setTime] = useState(new Date());
  useEffect(() => {
    const interval = setInterval(() => {
      setTime(new Date());
    }, 60_000);
    return () => {
      clearInterval(interval);
    };
  }, []);
  return (
    <TimeDiv>
      {time.getHours()}:{time.getMinutes().toString().padStart(2, "0")}
    </TimeDiv>
  );
}

export default Time;
